### PR TITLE
V3 endpoints

### PR DESCRIPTION
**Pull request by rsforbes**

### CODE REVIEW

**Comment by rsforbes** [comment]
@shufinskiy - GitHub needs a better branch commenting/discussion system where I can tag a line of code and at-mention you.

Few items:
1. My apologies for taking so long. I was so hyped on a little recursion cleanup and wound up with spaghetti. I'm shelving that for now. 😭 
2. We have a couple of broken methods within [http.py](https://github.com/rsforbes/nba_api/blob/be2f4d8b2ae1db2b0efd684e75f5a1b896e2481e/src/nba_api/stats/library/http.py#L23C11-L23C11): `get_normalized_json` and `get_normalized_dict`. These rely on the former JSON format that contained a `results` object. What do you think about filing a bug to fix later? 👍 
3. Between the R library and this library, you've chosen to drop some fields: `"gameId":"", "awayTeamId": ,"homeTeamId": `. Are you looking to keep this consistent with the previous endpoint results?👍 

Let me know your thoughts on 2 and 3.

**Comment by shufinskiy** [comment]
@rsforbes 

2. Yes, I agree. When writing code for V3, I thought about how to fix them so that they wouldn't break, but I couldn't, so I just made them empty.

3. Can I have an example of a V3 class that doesn't return a gameId? Because all tables in version 3 should have a gameId. I considered the awayTeamId and homeTeamId fields superfluous, there is a teamId field and, if necessary, you can restore this information.

**Comment by rsforbes** [comment]
@shufinskiy - 

3. My bad on the `gameId`, you are correct. It's the other two fields: `awayTeamId` and `homeTeamId` (see  [hoopR BoxScoreUsage3].(https://hoopr.sportsdataverse.org/reference/nba_boxscoreusagev3.html)) <-- Note: I'm not personally a fan of including it, simply because it's a little messy on the dataframe. It could be returned as a separate data object called `root`, `game`, or other.

Different question, and this could be useful: What are your thoughts on structuring the data similar to pandas.json_normalize? This would allow a couple of things:
1. Clear decomposition on nesting where we end up with `{parent}.{object}`, as in `statistics.percentageFieldGoalsMade`
2. This could allow the inverse of flat to hierarchal.
3. Aligns with the JSON very well
4. Supports deeper nesting which avoids naming conflicts.

**Comment by shufinskiy** [comment]
> Different question, and this could be useful: What are your thoughts on structuring the data similar to pandas.json_normalize?

@rsforbes 

I am not against such a decision, but so far I do not have a clear plan on how to implement it. I would suggest implementing an analog of pandas.json_normalize in future tasks, because this logic is hidden from the end user.

**Comment by rsforbes** [comment]
@shufinskiy - I've been through this code more than once. While there are always opportunities to improve, I don't see any of those improvements changing the library's response objects. The objects you've created meet the needs of the library. The code is really good; making it more dynamic would require a significant amount of more time. In short, excellent work!!!

---
### Areas of Note
#### Hierarchical Naming 
This makes it less readable and usable. I played around with this, and while I can modify your code to return something such as `statistics.fieldGoalPercentage` being unnecessary.

#### Testing
This does need to be completed; however, I don't see why this should prevent the merge. I'll create an issue for it.

####  Dynamic Recursion of JSON
Something that would be ideal; however, not necessary as it has no impact on performance or return values. Perhaps a future goal.

#### stats/__init__.py
This file needs the new endpoints added in. I'll get that done.

#### Release notes
I'll get these completed.

#### Splitting parser.py
Again, it's nice to have, but not a requirement. I'll log an issue for the future.

---
Excellent work! I look forward to further collaboration!!!

I should have a release out within the next couple of days.

# Thank you!

**Comment by shufinskiy** [comment]
@rsforbes good news. I hope we will be able to make the code even better in the future.

**Comment by rsforbes** [comment]
@shufinskiy - Can you take a quick look at my code commits? My apologies for the formatting change, skip those. I didn't realize I had `black` running. `black` is something I need to do in the future for the project.

Here are my changes
1. Added the new endpoints to `__init__.py` [change](https://github.com/rsforbes/nba_api/pull/10/commits/f8179d65366956ec9271bceb123afa91b60be103) file.
2. Renamed the boxscorescoreingv3 file to boxscorescoringv3 (dropped the extra e) [change](https://github.com/rsforbes/nba_api/pull/10/commits/296ec7bb450efe2595822383de3cd732b33088e9)
3. Unit Testing / Error Handling [change](https://github.com/rsforbes/nba_api/pull/10/commits/bebf5c1c75ed98a194f6648bfc8e9cee6fcf4e54#diff-e59d9471067252c94d4cf93402a37dea0952230eb22411bbc7a18ad70fbd0f07)
    - Wrote complete unit tests for NBAStatsResponse
    - Consolidated `get_data_sets_v3(self, endpoint)` into `get_data_set(self, endpoint = None)`

**Comment by shufinskiy** [comment]
@rsforbes 
All good. You did the right thing by combining the methods `get_data_sets_v3`and `get_data_set`

**Comment by rsforbes** [comment]
@shufinskiy - Closing this PR will open one against the primary repo and merge. Thank you for all of your help!!!

**Pull request closed without merging**
